version: 'serverconnection'

services:
  flaskapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

#ejecutar contenedor
#docker-compose up --build
#
